### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by k0fi** [jeroendk/go-vuejs-chat#3]
Hello Jeroenk,
Thanks for adding authentication but it seems to have still some bugs. 
I get `Login failed` when I try to register a user on a cache cleaned browser. 
Please investigate.

**Comment by jeroendk** [comment]
Hi @k0fi,

You mean, you get the error while logging in? Because I didn't implement a register function.

**Comment by k0fi** [comment]
Well I get this in `Registered users` form at `http://127.0.0.1:8080`.

**Comment by jeroendk** [comment]
@k0fi That's the log-in form for registered users. 
Make sure you insert a user, see the section "Database" @ https://www.whichdev.com/how-to-add-authentication-to-your-go-chat-application/

**Comment by k0fi** [comment]
I just downloaded the repo and work on that. 

```
curl --location --request GET 'localhost:8080/api/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "john",
    "Password":"password"
}'
```
Yeilds:
`{"status": "error"}
`

**Comment by jeroendk** [comment]
@kofi
Please check the tutorial, the insert command is commented out by default. 
Check it @ config/database.go

```
	// sqlStmt = `INSERT into user (id, name, username, password) VALUES
	// 				('` + uuid.New().String() + `', 'john', 'john','` + password + `')`

	// _, err = db.Exec(sqlStmt)
	// if err != nil {
	// 	log.Fatal("%q: %s\n", err, sqlStmt)
	// }
```

**Comment by k0fi** [comment]
I uncommented the insert part in `config/database.go`, deleted database and rebuild, and now I can get JWT token. How should I use that in the app?
