### ISSUE TITLE
How to deploy using nginx? 

### ISSUE THREAD

**Issue by hume12** [jeroendk/go-vuejs-chat#4]
Hello, 
Thanks for the great tutorial and  codebase. It works fine on localhost but I have difficulty deplying it on a real site. 
First of all since most browsers don't allow websocket over unencrypted connections, it seems that the chatroom domain works only with a ssl certificate. So I converted `http` in `app.js` `https` and `ws` to `wss`. So the modifed app.js looks like this:

var app = new Vue({
  el: '#app',
  data: {
    ws: null,
    serverUrl: "wss://" + location.host + "/ws",
    roomInput: null,
    rooms: [],
    user: {
      name: "",
      username: "",
      password: "",
      token: ""
    },
    users: [],
    initialReconnectDelay: 1000,
    currentReconnectDelay: 0,
    maxReconnectDelay: 16000,
    loginError: ""
  },
  mounted: function () {
  },
  methods: {
    connect() {
      this.connectToWebsocket();
    },
    async login() {
      try {
        const result = await axios.post("https://" + location.host + '/api/login', this.user);
       ...

But after doing so, I still have difficulty setting up an nginx config for my domain exmple.com. Here is my config:

```
server {
        listen 1.2.3.4:80;
     return 301 https://$host$request_uri;
}



server {
listen  443;
root /www/go/src/chat/public;


error_log /var/log/nginx/error.log;
access_log /var/log/nginx/access.log;


ssl on;
ssl_certificate /etc/ssl/certs/chat/fullchain.pem;
ssl_certificate_key /etc/ssl/certs/chat/privkey.pem;

 
location /  {
        proxy_pass http://127.0.0.1:8080;
        
        try_files $uri $uri/ /index.html;

}
 
}
```

I get this error in the browser:

```
GET https://myfancychatroom.com/api/ net::ERR_TOO_MANY_REDIRECTS
(anonymous) @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
Promise.then (async)
r.request @ isAxiosError.js:10
r.(anonymous function) @ isAxiosError.js:10
(anonymous) @ isAxiosError.js:10
login @ app2.js:28
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
original._wrapper @ vue.js:7547
app2.js:37 Error: Network Error
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.onerror (isAxiosError.js:10)
```
Really apprecite your help about this.

**Comment by jeroendk** [comment]
Hi, glad you like it! 

Are you running Nginx with docker? Is the Go app running on the same server as Nginx? Can you try and remove the "try_files" in the location block?

```
server {
    server_name myfancychatroom.com;
    listen  443 ssl;
    root /www/go/src/chat/public; 
    
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;    
    
    ssl on;
    ssl_certificate /etc/ssl/certs/chat/fullchain.pem;
    ssl_certificate_key /etc/ssl/certs/chat/privkey.pem;
    
    location / {
        proxy_pass http://localhost:8080;
    }
}
```

If you need the try files, I think you have to add them separately.

```
location / {
    try_files $uri $uri/ @goproxy;
}

location @goproxy {
    proxy_pass http://localhost:8080;
}
```
